src/core/urls.py
from django.urls import path
from .views import ( CheckoutView, product, HomeView, 
ItemDetailView, add_to_cart,remove_from_cart,OrderSummaryView, remove_single_item_from_cart,
PaymentView,MyProductsView, AboutView, ContactView)

app_name = 'core'

urlpatterns =[
    path('', HomeView.as_view(), name = 'home'),
    path('checkout/<slug>', CheckoutView.as_view(), name = 'checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name = 'order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name = 'product'),
    path('add-to-cart/<slug>/', add_to_cart, name = 'add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name = 'remove-from-cart'),
    path('remove-single-itemfrom-cart/<slug>/', remove_single_item_from_cart, name = 'remove-single-item-from-cart'),
    # path('payment/<payment_option>', PaymentView.as_view(), name = 'payment'),
    path('payment/', PaymentView.as_view(), name = 'payment'),
    path('my-products', MyProductsView.as_view(), name = 'my-products'),
    path('about', AboutView.as_view(), name = 'about'),
    path('contact', ContactView.as_view(), name = 'contact'),
] 

src/emmettshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/core/models.py
from django.conf import settings
from django.db import models
from django.db.models.base import ModelBase, ModelStateFieldsCacheDescriptor
from django.shortcuts import reverse
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)
class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank = True, null = True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description =models.TextField()
    image = models.ImageField()
    image_2 = models.ImageField(null = True)
    image_3 = models.ImageField(null = True)
    image_4 = models.ImageField(null = True)
    sold = models.BooleanField(default=False)
    dimension = models.CharField(max_length=100)
    featured = models.BooleanField(default=False, null = True)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs = {
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse('core:add-to-cart', kwargs = {
            'slug': self.slug
        })
    def get_remove_from_cart_url(self):
        return reverse('core:remove-from-cart', kwargs = {
            'slug': self.slug
        })
class ImageItem(models.Model):
    image = models.ImageField(upload_to = 'images/')
    default = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    device = models.CharField(max_length=20, null = True)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
    on_delete=models.CASCADE)

    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple = False)
    zip = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username
        
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    device = models.CharField(max_length=20, null = True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(null = True)
    ordered = models.BooleanField(default=False)

    billing_address = models.ForeignKey(BillingAddress, on_delete=models.SET_NULL, null = True)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

class Banner(models.Model):
    small_title = models.CharField(max_length=100)
    big_title = models.CharField(max_length=100)
    selected = models.BooleanField(null =True, default = False)
    image_1 = models.ImageField(upload_to='images/')
    image_2 = models.ImageField(upload_to='images/', null = True)
    image_3 = models.ImageField(upload_to='images/', null = True)
    slug = models.CharField(max_length=100)

class HomeAboutNote(models.Model):
    note = models.CharField(max_length=100)
class Home(models.Model):
    banner = models.ForeignKey(Banner, on_delete=models.CASCADE)
    about_title = models.CharField(max_length=100)
    small_title = models.CharField(max_length=100)
    about_image = models.ImageField(upload_to = 'images/')
    notes = models.ManyToManyField(HomeAboutNote)
    purchase_now_title =  models.CharField(max_length=100)
    purchase_now_description = models.CharField(max_length=100)
    selected = models.BooleanField(null = True, default=False)

    def __str__(self):
        return self.about_title

class About(models.Model):
    banner = models.ForeignKey(Banner, on_delete=models.CASCADE)
    about_title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/', null = True)
    small_title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    facebook = models.CharField(max_length=100)
    twitter = models.CharField(max_length=100)
    linkedin = models.CharField(max_length=100)
    selected = models.BooleanField(null = True, default=False)

    old_works_title = models.CharField(max_length=100)
    # old_works = models.ManyToManyField(Item, null = True)

class Contact(models.Model):
    banner = models.ForeignKey(Banner, on_delete=models.CASCADE)
    location_title = models.CharField(max_length=100)
    google_map_location = models.CharField(max_length=1000)
    about_office_title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    message_title = models.CharField(max_length=1000)
    facebook = models.CharField(max_length=100)
    twitter = models.CharField(max_length=100)
    linkedin = models.CharField(max_length=100)
    selected = models.BooleanField(null = True, default=False)




    

src/templates/about.html
{% extends 'base.html' %}
{% block content %}
    <!-- Page Content -->
    <div class="page-heading about-heading header-text" style = "background-image: url({{data.banner.image_1.url}});" >
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h4>{{data.banner.small_title}}</h4>
              <h2>{{ data.banner.big_title }}</h2>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="best-features about-features">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>{{data.about_title}}</h2>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-image">
              <img src="{{ data.image.url }}" alt="{{data.about_title}}">
            </div>
          </div>
          <div class="col-md-6">
            <div class="left-content">
              <h4>{{data.small_title}}</h4>
              <p>{{data.description}}</p>
              <ul class="social-icons">
                <li><a href="https://{{data.facebook}}"><i class="fa fa-facebook"></i></a></li>
                <li><a href="https://{{data.twitter}}"><i class="fa fa-twitter"></i></a></li>
                <li><a href="https://{{data.linkedin}}"><i class="fa fa-linkedin"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    
    <div class="team-members">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>{{data.old_works_title}}</h2>
            </div>
          </div>
          {% for item in old_works %}
          <div class="col-md-4">
            <div class="team-member">
              <div class="thumb-container">
                <img src="{{item.image.url}}" alt="">
           
              </div>
              <div class="down-content">
                <h4>{{item.title}}</h4>
                <span>{{item.dimension}}</span>
                <p>{{item.description}}</p>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>

{% endblock content %}

src/templates/banner.html
<div class="banner header-text">
    <div class="owl-banner owl-carousel">
      <div class="banner-item-01" style = "background-image: url({{banner.image_1.url}});">
        <div class="text-content">
          <h4 style ="color:cadetblue;">{{ banner.small_title }}</h4>
          <h2>{{ banner.big_title }}</h2>
        </div>
      </div>
      <div class="banner-item-02" style = "background-image: url({{banner.image_2.url}});">
        <div class="text-content">
          <h4>{{ banner.small_title }}</h4>
          <h2>{{ banner.big_title }}</h2>
        </div>
      </div>
      <div class="banner-item-03" style = "background-image: url({{banner.image_3.url}});">
        <div class="text-content">
          <h4>{{ banner.small_title }}</h4>
          <h2>{{ banner.big_title }}</h2>
        </div>
      </div>
    </div>
  </div>

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title>Emmett Art Studio</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-sixteen-1.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.css' %}">

    <script tpye = "text/javascript">

      function getCookie(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }

      function uuid(){
        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c){
          var r = Math.random() *16|0, v=c=='x'?r:(r&0x3|0x8);
          return v.toString(16);
        })
      }
      
      let device = getCookie('device')

      if(device == null || device == undefined){
        device = uuid()
      }
      document.cookie = 'device='+device+';domain=;path=/'
    </script>
  </head>

  <body>
{% include "header.html" %}
{% include 'preloader.html'%}
{% if messages %}
{% for message in messages %}
<div class = "alert alert-{{ message.tags }}" role = "alert">
    {{ message }}
</div>
{% endfor %}    
{% endif %}
{% block content %}

{% endblock content %}
{% include "footer.html"%}

<script src="{% static 'jquery/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- Additional Scripts -->
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/owl.js' %}"></script>
<script src="{% static 'js/slick.js' %}"></script>
<script src="{% static 'js/isotope.js' %}"></script>
<script src="{% static 'js/accordions.js' %}"></script>
</body>

</html>

src/templates/checkout-page.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

  <!--Main layout-->
  <main class=" pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center pt-2">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
      
            <form class="card-body" method="POST"> {% csrf_token %}
              <!--address-->
              <div class="md-form mb-5">
                {{ form.street_address }}
              </div>
              <!--address-2-->
              <div class="md-form mb-5">
                {{ form.apartment_address }}
              </div>
              <!--Grid row-->
              <div class="row">
                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">
                  {{ form.country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>
                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">
                  {{ form.zip}}
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr>

              <div class="custom-control custom-checkbox">
                <input {% if form.same_billing_address.value %} checked {% endif %} type="checkbox" class="custom-control-input" name = "same_billing_address" id="same-address">
                <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input {% if form.save_info.value %} checked {% endif %}type="checkbox" class="custom-control-input" name = "save_info" id="save-info">
                <label class="custom-control-label" for="save-info">Save this information for next time</label>
              </div>
              <hr>
              <div class="d-block my-3">
               <!-- {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value = "{{ value }}"type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %} -->
              </div>
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{item.titel}}</h6>
                <small class="text-muted">{{item.description}}</small>
              </div>
              <span class="text-muted">${{item.price}}</span>
            </li>
            
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Tax</h6>
                <!-- <small>EXAMPLECODE</small> -->
              </div>
              <span class="text-success">$0</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>${{ item.price }}</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          <!-- <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
              </div>
            </div>
          </form> -->
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
{% endblock content %}

src/templates/contact.html
{% extends 'base.html'%}
{% block content %}

    <!-- Page Content -->
    <div class="page-heading contact-heading header-text" style = "background-image: url({{data.banner.image_1.url}});">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h4>{{data.banner.small_title}}</h4>
              <h2>{{ data.banner.big_title }}</h2>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="find-us">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>{{data.location_title}}</h2>
            </div>
          </div>
          <div class="col-md-8">
<!-- How to change your own map point
	1. Go to Google Maps
	2. Click on your location point
	3. Click "Share" and choose "Embed map" tab
	4. Copy only URL and paste it within the src="" field below
-->
            <div id="map">
              <iframe src="{{data.google_map_location}}" width="100%" height="330px" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
          </div>
          <div class="col-md-4">
            <div class="left-content">
              <h4>{{data.about_office_title}}</h4>
              <p>{{data.description}}</p>
              <ul class="social-icons">
                <li><a href="https://{{data.facebook}}"><i class="fa fa-facebook"></i></a></li>
                <li><a href="https://{{data.twitter}}"><i class="fa fa-twitter"></i></a></li>
                <li><a href="https://{{data.twitter}}"><i class="fa fa-linkedin"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    
    <div class="send-message">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Send us a Message</h2>
            </div>
          </div>
          <div class="col-md-8">
            <div class="contact-form">
              <form id="contact" action="" method="post">
                <div class="row">
                  <div class="col-lg-12 col-md-12 col-sm-12">
                    <fieldset>
                      <input name="name" type="text" class="form-control" id="name" placeholder="Full Name" required="">
                    </fieldset>
                  </div>
                  <div class="col-lg-12 col-md-12 col-sm-12">
                    <fieldset>
                      <input name="email" type="text" class="form-control" id="email" placeholder="E-Mail Address" required="">
                    </fieldset>
                  </div>
                  <div class="col-lg-12 col-md-12 col-sm-12">
                    <fieldset>
                      <input name="subject" type="text" class="form-control" id="subject" placeholder="Subject" required="">
                    </fieldset>
                  </div>
                  <div class="col-lg-12">
                    <fieldset>
                      <textarea name="message" rows="6" class="form-control" id="message" placeholder="Your Message" required=""></textarea>
                    </fieldset>
                  </div>
                  <div class="col-lg-12">
                    <fieldset>
                      <button type="submit" id="form-submit" class="filled-button">Send Message</button>
                    </fieldset>
                  </div>
                </div>
              </form>
            </div>
          </div>
         
        </div>
      </div>
    </div>

   
{% endblock content %}

src/templates/footer.html
 
    <footer>
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="inner-content">
                <p>Copyright &copy; 2021 Emmett Studio.
              
              - CREATED: <a rel="nofollow noopener" href="https://kavianhabib.github.io/" target="_blank"> HABIBUDDIN </a></p>
              </div>
            </div>
          </div>
        </div>
      </footer>

src/templates/header.html
<header class="">
    <nav class="navbar navbar-expand-lg">
      <div class="container">
        <a class="navbar-brand" href="{% url 'core:home' %}"><h2>Emmett <em style = "color:blueviolet;">Studio</em></h2></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            
            <li {% if request.path == '/' %} class="nav-item  active" {% else %}class="nav-item"{% endif %}>
              <a class="nav-link" href="{% url 'core:home' %}">Home
                
                <span class="sr-only">(current)</span>
              </a>
            </li> 
            <li {% if request.path == '/my-products' %} class="nav-item  active" {% else %}class="nav-item"{% endif %}>
              <a class="nav-link" href="{% url 'core:my-products' %}">Our Products</a>
            </li>
            <li {% if request.path == '/about' %} class="nav-item  active" {% else %}class="nav-item"{% endif %}>
              <a class="nav-link" href="{% url 'core:about' %}">About Us</a>
            </li>
            <li {% if request.path == '/contact' %} class="nav-item  active" {% else %}class="nav-item"{% endif %}>
              <a class="nav-link" href="{% url 'core:contact' %}">Contact Us</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>

src/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- ***** Preloader Start ***** -->
    
    <!-- ***** Preloader End ***** -->
    <!-- Banner Starts Here -->
    {% include "banner.html "%}
    <!-- Banner Ends Here -->

    <div class="latest-products">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Featured Arts</h2>
              <a href="{% url 'core:my-products' %}">view all products <i class="fa fa-angle-right"></i></a>
            </div>
          </div>
          {% if object_list %}
          {% for item in object_list %}
          {% if not item.sold %}
          <div class="col-md-4">
            <div class="product-item">
              <a href="{{ item.get_absolute_url }}"><img src="{{ item.image.url }}" alt="{{ item.title }}"></a>
              <div class="down-content">
                <a href="#"><h4>{{ item.title }}</h4></a>
                <h6>${{ item.price }}</h6>
                <p>{{ item.description}}</p>
                <!-- <ul class="stars">
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                </ul>
                <span>Reviews (24)</span> -->
              </div>
            </div>
          </div>
          {% endif %}
          {% endfor %}
          {% endif %}
        </div>
      </div>
    </div>

    <div class="best-features">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>{{title}}</h2>
            </div>
          </div>
          <div class="col-md-6">
            <div class="left-content">
              <h4>{{ small_title}}</h4>
              <!-- <p><a rel="nofollow" href="{% url 'core:about' %}" target="_parent">This studio</a> write the whatever you want here <a rel="nofollow" href="{% url 'core:contact' %}">Contact us</a> for more info.</p> -->
              <ul class="featured-list">
                {% for note in notes %}
                <li><a href="#">{{note.note}}</a></li>
                {% endfor %}
              </ul>
              <a href="{% url 'core:about' %}" class="filled-button">Read More</a>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-image">
              <img src="{{ image.url }}" alt="">
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="inner-content">
              <div class="row">
                <div class="col-md-8">
                  <h4>{{purchase_now_title}}</h4>
                  <p>{{purchase_now_description}}</p>
                </div>
                <div class="col-md-4">
                  <a href="{% url 'core:my-products' %}" class="filled-button">Purchase Now</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  
    <!-- Bootstrap core JavaScript -->



    <script language = "text/Javascript"> 
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>


{% endblock content %}

src/templates/preloader.html
<div id="preloader">
    <div class="jumper">
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>  

src/templates/product-page.html
{% extends 'base.html'%}
{% block content %}
  <!--Main layout-->
  <main class="pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{object.image.url}}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <!-- <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a> -->
        
            </div>

            <p class="lead">
              {% if object.discount_price %}

              <span class="mr-1">
                <del>${{ object.price}}</del>
              </span>
              
              <span>${{ object.discount_price }}</span>
              {% else %}
              <span>${{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{object.description}}</p>
            <p class="lead font-weight-bold">Dimensions</p>

            <p>{{object.dimension}}</p>

            <!-- <form class="d-flex justify-content-left">
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> -->

            <a class="btn btn-primary btn-md my-0 p" href ="{% url 'core:checkout' object.slug %}">BUY
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <!-- <a class="btn btn-danger btn-md my-0 p" href ="{{object.get_remove_from_cart_url}}">remove from cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a> -->
          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">
        <!--Grid column-->
        <div class="col-md-6 text-center">
          <h4 class="my-4 h4">Additional information</h4>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
      <!--Grid row-->
      
      <div class="row wow fadeIn">
        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">
          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">
        </div>
        <!--Grid column-->
        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">
          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">
        </div>
        <!--Grid column-->
        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">
          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </div>
  </main>
  <!--Main layout-->
{% endblock content %}